service: sandbox-serverless-vpc

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  region: ap-northeast-1
  environment:
    HELLO: world

package:
  exclude:
    - __test__
    - .circleci/**
    - .git/**
    - bin/**
    - .*
    - jest*
    - tsconfig.*
    - package.json
    - package-lock.json
    - yarn.lock
    - README.md

functions:
  hello:
    handler: src/hello.handler
    events:
      - http:
          path: hello
          method: GET
          integration: lambda
          response:
            statusCodes:
              200:
                pattern: ""
